name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.x'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        source-url: https://nuget.pkg.github.com/Liveron/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_PACKAGES_ACCESS_TOKEN }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Install Docker using Docker's official script
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh ./get-docker.sh --dry-run
      continue-on-error: false

    - name: Install Docker Compose
      run: docker-compose --version

#     - name: Test
#       run: dotnet test --no-build 

#   pack-and-publish:
#     needs: build-and-test
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v4

#     - name: Setup .NET
#       uses: actions/setup-dotnet@v4
#       with:
#         dotnet-version: ${{ env.DOTNET_VERSION }}
#         source-url: https://nuget.pkg.github.com/Liveron/index.json
#       env:
#         NUGET_AUTH_TOKEN: ${{ secrets.NUGET_PACKAGES_ACCESS_TOKEN }}

#     - name: Pack
#       run: dotnet pack --configuration Release -o ./artifacts

#     - name: Publish to GitHub Packages
#       working-directory: artifacts
#       run: | 
#         dotnet nuget push * --source "https://nuget.pkg.github.com/Liveron/index.json" \
#         --api-key ${{ secrets.NUGET_PACKAGES_ACCESS_TOKEN }} \
#         --skip-duplicate